### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Dylan-86** [chris2k90/plasma-nordvpn#42] opened 2024-08-13 12:16 UTC
**Describe the bug**
There is just one server available in the list, "Albania". It seems that only the first country in alphabetical order is loaded.

**To Reproduce**
1. Install
2. Click on the icon 
3. You see only one server available

**Expected behavior**
Complete list of servers

**Screenshots**
![image](https://github.com/user-attachments/assets/2215c7b8-0025-4d1f-8ef1-1194be9e7d25)

**Desktop (please complete the following information):**
 - Distribution: Ubuntu 22.04
 - KDE Plasma. 5.24.7
 - NordVPN Version 3.18.3

![image](https://github.com/user-attachments/assets/15b295d2-b94d-426a-a99e-0c05d5e21d30)

**Comment by korapp** [comment] 2024-08-13 12:41
I assume you were using plasmoid before version 0.5.1. Did you log out or restart plasma (`plasmashell --replace`) after update?

**Comment by Dylan-86** [comment] 2024-08-13 12:49
You're right.
Just done and it fixed the issue.

Thanks!

**Comment by korapp** [comment] 2024-08-13 12:49
Duplicate of #41

**Closed as completed by korapp** 2024-08-13 12:49 UTC
Labels: bug
